services:
  - type: web
    name: DexProxy
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: MORALIS_API_KEY
        sync: false
